<a href="https://colab.research.google.com/github/ImNotARobot00/learn-git/blob/master/TensorFlow_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Imports

In [4]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.14.0


#Load the dataset


In [5]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


#Build the model

In [8]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0,2),
    tf.keras.layers.Dense(10),
])

#this returns a vector of log-odds

In [9]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.02708659, -1.0434222 , -0.5582782 ,  0.45524076, -0.94367146,
         0.39931476, -0.45653337,  0.19059592,  0.20365587, -0.5384668 ]],
      dtype=float32)

#Returns the probabilities

In [11]:
tf.nn.softmax(predictions).numpy()

array([[0.10805503, 0.03910714, 0.06352598, 0.17503186, 0.0432093 ,
        0.16551171, 0.07032967, 0.13433318, 0.13609907, 0.06479707]],
      dtype=float32)

#defines the loss dunction

In [12]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

Returns the scalar loss

In [13]:
loss_fn(y_train[:1], predictions).numpy()

1.7987132

Configure and compile the model

In [14]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

Train and evaluate the model

In [16]:
model.fit(x_train, y_train, epochs=5) #adjust the parameters of the model

Epoch 1/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0347 - accuracy: 0.9895
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0267 - accuracy: 0.9917
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0234 - accuracy: 0.9924
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0175 - accuracy: 0.9945
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0159 - accuracy: 0.9948


In [17]:
model.evaluate(x_test, y_test, verbose=2) #checks model performance

313/313 - 1s - loss: 0.0849 - accuracy: 0.9785 - 725ms/epoch - 2ms/step


[0.08494400978088379, 0.9785000085830688]

In [19]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])                                     #returns a probability for the model

In [20]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.4745501e-10, 1.2645936e-11, 4.8407795e-08, 9.3274130e-06,
        4.7688524e-14, 6.6181821e-10, 4.4980864e-16, 9.9999046e-01,
        7.1189628e-09, 7.4550655e-08],
       [3.5799766e-10, 5.9491308e-06, 9.9999356e-01, 3.4278937e-08,
        9.9964982e-17, 3.8655114e-11, 1.1111714e-11, 1.1702558e-18,
        4.3587346e-07, 4.9669305e-18],
       [6.8575634e-10, 9.9994218e-01, 6.2404124e-06, 3.0080508e-07,
        5.2661039e-07, 5.1819370e-08, 1.1976765e-07, 2.9495492e-05,
        2.1141142e-05, 8.9317420e-10],
       [9.9997699e-01, 1.8549435e-09, 6.3324346e-06, 3.4054032e-10,
        6.7944645e-09, 1.3350976e-09, 1.5890388e-05, 7.7456519e-07,
        2.7819138e-09, 8.2329372e-11],
       [5.7569022e-10, 4.1982451e-10, 6.9280266e-09, 1.0351554e-12,
        9.9977905e-01, 2.5851059e-11, 3.8239027e-06, 1.7901216e-07,
        1.5411096e-08, 2.1691348e-04]], dtype=float32)>